# Generated by Django 5.1 on 2024-09-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_comment_body_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='social.post'),
            preserve_default=False,
        ),
    ]
