# Generated by Django 5.1 on 2024-09-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_replycomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='perent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.comment'),
        ),
    ]
