# Generated by Django 5.1 on 2024-09-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_perent_comment_replycomment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.comment'),
        ),
    ]
