# Generated by Django 5.1 on 2024-09-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_replycomment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='social.replycomment'),
        ),
    ]
