# Generated by Django 5.1 on 2024-10-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_post_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
